apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viken-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: viken.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-integration-frontend_viken-no"
      - op: replace
        path: "/spec/orgId"
        value: "viken.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "/viken-no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/viken-no"
    target:
      kind: Application
      name: fint-flyt-integration-frontend

  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: "/viken-no"
    target:
      kind: FLAISSso
      name: fint-flyt-auth-forward-sso

