
---

---
<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-integration-frontend
  name: fint-flyt-integration-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-integration-frontend
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-integration-frontend
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-integration-frontend:dummy
          name: fint-flyt-integration-frontend
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: Europe/Oslo
=======

>>>>>>> a5ac7a8 (Added kustomize and GA config)
