version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "Europe/Oslo"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      timezone: "Europe/Oslo"
    groups:
      navikt-minor-patch:
        patterns:
          - "@navikt/*"
        update-types:
          - "minor"
          - "patch"
      navikt-major:
        patterns:
          - "@navikt/*"
        update-types:
          - "major"
      mui-minor-patch:
        patterns:
          - "@mui/*"
          - "@types/mui"
          - "@emotion/*"
        update-types:
          - "minor"
          - "patch"
      mui-major:
        patterns:
          - "@mui/*"
          - "@types/mui"
          - "@emotion/*"
        update-types:
          - "major"
      react-minor-patch:
        patterns:
          - "react"
          - "react-dom"
          - "react-*"
          - "@types/react"
          - "@types/react-dom"
          - "@types/react-*"
        update-types:
          - "minor"
          - "patch"
      react-major:
        patterns:
          - "react"
          - "react-dom"
          - "react-*"
          - "@types/react"
          - "@types/react-dom"
          - "@types/react-*"
        update-types:
          - "major"
      linting-minor-patch:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      linting-major:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "prettier"
        update-types:
          - "major"
      vite-minor-patch:
        patterns:
          - "vite"
          - "vitest"
          - "@vitejs/*"
          - "@types/vite"
        update-types:
          - "minor"
          - "patch"
      vite-major:
        patterns:
          - "vite"
          - "vitest"
          - "@vitejs/*"
          - "@types/vite"
        update-types:
          - "major"
      server-minor-patch:
        patterns:
          - "express"
          - "helmet"
          - "morgan"
          - "log4js"
        update-types:
          - "minor"
          - "patch"
      server-major:
        patterns:
          - "express"
          - "helmet"
          - "morgan"
          - "log4js"
        update-types:
          - "major"
