version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "Europe/Oslo"
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      timezone: "Europe/Oslo"
    groups:
      navikt:
        patterns:
          - "@navikt/*"
      mui:
        patterns:
          - "@mui/*"
      emotion:
        patterns:
          - "@emotion/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      types:
        patterns:
          - "@types/*"
      vite:
        patterns:
          - "vite"
          - "vitest"
          - "@vitejs/*"
