version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "Europe/Oslo"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Europe/Oslo"