apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-flyt-integration-frontend
  app.kubernetes.io/instance: fint-flyt-integration-frontend_vlfk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: fint-flyt
  fintlabs.no/team: flyt
  fintlabs.no/org-id: vlfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/routes/0/match"
        value: "Host(`flyt.vigoiks.no`) && PathPrefix(`/alpha/vlfk-no`) && !PathPrefix(`/alpha/vlfk-no/api`)"
    target:
      kind: IngressRoute
      name: fint-flyt-integration-frontend
