apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD
namespace: vlfk-no
=======
>>>>>>> a5ac7a8 (Added kustomize and GA config)
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-flyt-integration-frontend
  app.kubernetes.io/instance: fint-flyt-integration-frontend_vlfk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: fint-flyt
  fintlabs.no/team: flyt
  fintlabs.no/org-id: vlfk.no
patches:
  - patch: |-
      - op: replace
<<<<<<< HEAD
        path: "/spec/routes/0/match"
        value: "Host(`flyt.vigoiks.no`) && PathPrefix(`/alpha/vlfk-no`)"
    target:
      kind: IngressRoute
      name: fint-flyt-integration-frontend
=======
        path: "/data/BASE_PATH"
        value: "/alpha/vlfk-no"
    target:
      kind: ConfigMap
      name: fint-flyt-integration-frontend

>>>>>>> a5ac7a8 (Added kustomize and GA config)
