apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-integration-frontend_vestfoldfylke-no"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "/vestfoldfylke-no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/vestfoldfylke-no"
    target:
      kind: Application
      name: fint-flyt-frontend

  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: "/vestfoldfylke-no"
    target:
      kind: FLAISSso
      name: fint-flyt-auth-forward-sso

