apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-integration-frontend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-integration-frontend
    app.kubernetes.io/instance: fint-flyt-integration-frontend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-integration-frontend:sha-0000000
  url:
    hostname: flyt.vigoiks.no
    basePath: path
  ingress:
    enabled: true
    middlewares:
      - fint-flyt-integration-frontend
  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }