apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-flyt-integration-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-integration-frontend:dummy
          name: fint-flyt-integration-frontend
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fint-flyt-integration-frontend