apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-frontend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-frontend
    app.kubernetes.io/instance: fint-flyt-frontend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-frontend:sha-0000000
  url:
    hostname: flyt.vigoiks.no
    basePath: path
  ingress:
    enabled: true
    middlewares:
      - fint-flyt-auth-forward-sso
  env:
    - name: VITE_BASE_PATH
      value: path
    - name: VITE_API_AUTH
      value: 'http://fint-flyt-authorization-service:8080'
    - name: VITE_API_CONF
      value: 'http://fint-flyt-configuration-service:8080'
    - name: VITE_API_HISTORY
      value: 'http://fint-flyt-history-service:8080'
    - name: VITE_API_INST
      value: 'http://fint-flyt-instance-service:8080'
    - name: VITE_API_INT
      value: 'http://fint-flyt-integration-service:8080'
    - name: VITE_API_ARCH
      value: 'http://fint-flyt-archive-gateway:8080'
    - name: VITE_API_DISC
      value: 'http://fint-flyt-discovery-service:8080'
    - name: VITE_API_VALUE_CONV
      value: 'http://fint-flyt-value-converting-service:8080'
  resources:
    limits:
      memory: "256Mi"
      cpu: "250m"
    requests:
      memory: "96Mi"
      cpu: "50m"
  restartPolicy: Always
  replicas: 1
  probes:
    startup:
      path: /health
      port: 8000
      initialDelaySeconds: 70
      failureThreshold: 12
      periodSeconds: 10
      timeoutSeconds: 3
