apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
<<<<<<< HEAD
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml
  - config-map.yaml
=======
  - configmap.yaml
  - deployment.yaml
  - ingress-route.yaml
  - service.yaml

>>>>>>> a5ac7a8 (Added kustomize and GA config)
