apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfylke-no

resources:
  - ../../../base2

commonLabels:
  app.kubernetes.io/instance: fint-flyt-integration-frontend_trondelagfylke_no
  fintlabs.no/org-id: trondelagfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "trondelagfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/alpha/trondelagfylke-no"
    target:
      kind: Application
      name: fint-flyt-integration-frontend

  - patch: |-
      - op: replace
        path: "/spec/basePath"
        value: "/alpha/trondelagfylke-no"
    target:
      kind: FLAISSso
      name: fint-flyt-integration-frontend

