name: build
on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.0.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Get repo name
        id: get_repo
        run: echo ::set-output name=REPO::${GITHUB_REPOSITORY#*/}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build artefacts
        run: |
          npm run build
          mkdir data
          cp ./build/libs/${GITHUB_REPOSITORY#*/}-*.jar ./data/app.jar
          echo "Branch: ${{ github.ref}}"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{steps.get_repo.outputs.REPO}}
          path: ./data/app.jar

## Uncomment to trigger a build and publish image to ACR
      - name: Start publish workflow
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUBACTION_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-to-publish

