name: Deploy
on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: fintlabsacr
  ALPHA_CLUSTER_NAME: aks-alpha-fint-2021-11-18
  ALPHA_CLUSTER_RESOURCE_GROUP: rg-aks-alpha
  APP_NAME: fint-skjema-integration-frontend


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Set the target Alpha cluster.
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AKS_ALPHA_FINT_GITHUB }}'
          cluster-name: ${{ env.ALPHA_CLUSTER_NAME }}
          resource-group: ${{ env.ALPHA_CLUSTER_RESOURCE_GROUP }}

      - name: Deploy to Alpha
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            viken-no-k8s.yaml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          namespace: viken-no
